[package]
name = "resolver_pool"
version = "0.1.0"
authors = ["stuart nelson <stuartnelson3@gmail.com>"]

[dependencies]
crossbeam = "^0.4"
trust-dns = "^0.15"
trust-dns-resolver = "^0.10"
env_logger = "^0.5"
log = "^0.4"
